title: BRONNN蜀黍的小屋
domain: jtskyin.github.com
markdown: rdiscount
lsi: false
permalink: /:year/:month/:day/:title/
category_dir: ../categories/
tag_dir: ../tags/
tag_title_prefix: 'Tag: '
safe: false
paginate: 6
exclude: ['README.markdown', 'README_FOR_COLLABORATORS.markdown', 'Gemfile.lock', 'Gemfile']
